### ISSUE TITLE
[BUG]: Casting to Nest devices broken

### ISSUE THREAD

**Issue by pannal** [Isaaker/Spotify-AdsList#26]
### What happened?

When using this list at least with Adguard Home, casting to Nest (mini) devices using android phones' Spotify app doesn't work. The app never properly connects to the playback devices.

I believe in order for casting to work again, one has to whitelist:
```
@@||cast.scdn.co^$important
@@||gae-spclient.spotify.com^$important
@@||gew-spclient.spotify.com^$important
```

### Browser

Other (Tell us the name the name in the box below)

### Tell us the name the name of your browser if you select Other

Spotify app

### Browser Version

-

### Operative System (OS)

Android (Google)

### OS Version

-

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @pannal, thanks for the report.

I will remove the ``cast.scdn.co`` from the blocklist for the next PR.

At the moment I don't see any need to add the domain to the whitelist, as there have been no problems with redirects yet ([you can learn more about how we use the whitelist here](https://spotify.piscinadeentropia.es/docs_installation/#5-add-spotify-ads-list-whitelist-to-your-adblocker)).

If you could test the new version of the whitelist with the changes made, it would help us to know if the changes made fixed the problem.

Thanks.

**Comment by Isaaker** [comment]
Hi @pannal, sorry for the wait. I have added new changes to the list in the last PR, among them I have removed the domain I told you about. Could you test it and let me know if it works.

Thanks

**Comment by Isaaker** [comment]
Oh, sorry I just didn't noticed about the 4. 

I would include it now and it would be available in some minutes.

Sorry, but I'm very distracted by #75 , I have some different systems affected by the bug apart from the docs of this project.

Thanks again for your contribution
