### ISSUE TITLE
New Testing Device: Google Pixel 4a / Android 13

### ISSUE THREAD

**Issue by mfjt** [Isaaker/Spotify-AdsList#3]
### Platform

App

### Device

Google Pixel 4a

### OS & Version

Android 13

### Testing Date

2024-04-19

### Status

ERROR

### List Type

Adguard

### Extra Info about the testing

I added your filter to AdGuard as DNS filter.
CNAME record from `login5.spotify.com` to `edge-web.dual-gslb.spotify.com` blocked.

![Screenshot of request details](https://github.com/Isaaker/Spotify-AdsList/assets/176216/cd3e2ef6-de6a-47b6-8440-32691e3e348e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by mfjt** [comment]
Even the rule to block `mobile-ap.spotify.com` seems to be recognized as an offline mode.

**Comment by Isaaker** [comment]
Hi @mfjt, I'm checking the issue, thanks for the report.

**Comment by Isaaker** [comment]
I have reviewed the domains you provided and removed them from the lists. Please, check now the list from https://raw.githubusercontent.com/Isaaker/Spotify-AdsList/Developer/Lists/adguard.txt , to verify that it does not give problems, and to be able to pass it to main.

**Comment by mfjt** [comment]
@Isaaker Thanks! It's works well👍
