### ISSUE TITLE
[BUG]: Nest Mini devices can't use Spotify (fix included)

### ISSUE THREAD

**Issue by pannal** [Isaaker/Spotify-AdsList#38]
### What happened?

With this blocklist enabled, Nest Mini devices can't be properly cast towards using the Spotify mobile app and when trying to play songs from Spotify via voice command, it simply doesn't play.

### Platform

Smart Home Devices (such as speakers)

### Device

Google Nest Mini

### OS & Version

-

### Relevant log output

```shell
-
```

### Extra Info about the bug

This can be fixed by whitelisting the following domain for those specific clients:
```
@@||seektables.scdn.co^$client='xxx.xxx.xxx.xxx'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @pannal, thanks for the report. Adding to whitelist.
