### ISSUE TITLE
[BUG]: FB Messenger Blocked

### ISSUE THREAD

**Issue by HeyItsJono** [Isaaker/Spotify-AdsList#46]
### Contact Details

Reply Here

### What happened?

This blocklist blacklists FB Messenger domains, preventing access. These have nothing to do with Spotify, not sure why this list touches them...

![image](https://github.com/user-attachments/assets/08da2ad5-0d6a-4916-a98d-54091706ff07)

### Platform

Web App

### Device

Adguard Home

### OS & Version

Adguard Home

### Browser & Version (If applicable)

Adguard Home

### Relevant log output

```shell
Nil
```

### Extra Info about the bug

Nil

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hello, thanks for the report. That's definitely wrong, I will check that and fix it when I have time (give me some days).

Sometimes, when I modify the blocklist I include domains by error, but it's easy to fix.

**Comment by HeyItsJono** [comment]
No stress, thanks for taking a look

**Comment by Isaaker** [comment]
Hi, I think the problems are fixed, you can checkout #50 to see the changes. 

Also, sorry for the commits mess, I got the wrong branch and made a huge mess.

Have a nice day 🙂

**Comment by HeyItsJono** [comment]
Sweet thank you! Testing now, the issue appears to be resolved, though might be because my devices' DNS caches havent refreshed yet. I'll keep you posted but as of rn appears fixed :)
