### ISSUE TITLE
[BUG]: Adguard Home on Nest Devices prevents playback

### ISSUE THREAD

**Issue by HeyItsJono** [Isaaker/Spotify-AdsList#47]
### Contact Details

Reply Here

### What happened?

With this list enabled in Adguard Home, on Nest devices with Spotify casting to them via a phone app, ads will still appear after a certain number of songs. Those ads will register on the screen/in the phone app, but they will not play any audio, and will just hang at 0:00min, preventing all further playback. They cannot be skipped.

### Platform

Web App

### Device

Adguard Home, Google Nest Hub 2nd Gen.

### OS & Version

Latest compatible Android.

### Relevant log output

```shell
Nil
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
I will also check this one, I have to research more because other people reported this problem but I don't have lot of info because I don't have a Google Nest device.

**Comment by HeyItsJono** [comment]
All good, let me know if there's something I can do to help you test

**Comment by Isaaker** [comment]
Hi, I think the problems are fixed, you can checkout #50 to see the changes. 

Also, sorry for the commits mess, I got the wrong branch and made a huge mess.

Have a nice day 🙂
