### ISSUE TITLE
New Testing Device: Linux Laptop / Fedora Workstation 40

### ISSUE THREAD

**Issue by SudoVanilla** [Isaaker/Spotify-AdsList#6]
### Contact Details

korbs@sudovanilla.com

### Platform

App

### Device

Laptop

### OS & Version

Fedora Workstation 40

### Testing Date

21/04/24

### Status

OK

### List Type

Adguard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @SudoVanilla, thanks for reporting a new testing device. I will add it to the README table.
