### ISSUE TITLE
Spotify desktop app music stops playing even after whitelisting domains [Mac - Adguard] / [MacOS, Sonoma 14.5]

### ISSUE THREAD

**Issue by y2kviv** [Isaaker/Spotify-AdsList#9]
### Platform

App

### Device

Mac

### OS & Version

MacOS, Sonoma 14.5

### Browser & Version (If applicable)

Chrome (v125.0.6422.142)

### Testing Date

6/6/2024

### Status

ERROR

### List Type

Adguard

### Extra Info about the testing

As per the instructions, i have used the Adguard compatible blacklist and manually whitelisted the 4 domains provided. Here are the 2 issues i noticed.

1. Although my spotify desktop app (Mac) starts playing for few seconds and then it abruptly stops. As soon i disable Spotify ads blacklist filter in adguard it start playing the music again.

2. Empty ad banner containers are still visible after blocking the ads in the home screen (Top) and playlist/album (bottom).

Can you please look into these issues?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Hi @y2kviv, thanks for contributing to the repo.

The first problem seems to be a problem with a domain that was accidentally blocked and therefore it is impossible to download music from Spotify's servers. So I will check the list for the domain that may be causing the problem for your current configuration [Mac - Adguard] / [MacOS, Sonoma 14.5].

Likewise, it would help me if you could include any list of Spotify domains that you see being blocked when using the app.

The second problem is completely normal. By using Spotify Ads List you block via Adguard the domains from where your Spotify application receives the ads, so even if you don't receive the ads, Spotify still reserves a place to insert them.

Until I fix it, I will include the bug in the README on the main page, Thanks for the report.

**Comment by Isaaker** [comment]
Hi @y2kviv, I have been checking the first problem you mentioned. And it works for me with the Spotify app on macOS Sonoma 14.5, although I use PiHole and it may also be that being in another country or different region some things change.

Would it be possible for you to send me a list of the domains that your AdGuard blocks when you use it with Spotify?

Thanks

**Comment by Isaaker** [comment]
I have not heard back from you in the last few days, so I will close the issue and mark it as solved since I have not detected any problem with the domains currently listed.

However, if you want to reopen the issue, do not hesitate to contact me.

Thanks
